### ISSUE TITLE
LESS and/or SASS version needed

### ISSUE THREAD

**Issue by glebcha** [cmaddux/littlebox#12]
It'll be better for those who use preprocessors as well as for maintainers/forkers.

**Comment by cmaddux** [comment]
I definitely agree, this is something I will be working on in the next week or two. I will try to add both SASS and LESS versions if time permits. Thanks for the suggestion, I'll give you an update, as soon as I've made some headway on this.

**Comment by glebcha** [comment]
Thanks, will watch and fork then :thumbsup:

**Comment by cmaddux** [comment]
Put together a LESS version in the development branch. Still working on cleaning it up (and haven't worked much with LESS), so if you have any feedback, I'd really appreciate it!
