### ISSUE TITLE
include package.json and minifier scripts

### ISSUE THREAD

**Issue by tracker1** [cmaddux/littlebox#2]
I'd be happy to add this if you like on monday... but I would suggest doing a package.json with a peerDependency for bootstrap, and include any build/minifier tools and scripts in the package.json... so you can simply `npm run build` ... also, publishing to npm of course.

In addition, would keep the source under `lib/` or `src/` and the build versions under `dist/` as a structural point...

Nice work by the way.

**Comment by cmaddux** [comment]
Thanks for taking a look! I should be able to handle publishing to npm, but a bit of guidance regarding a package.json would be a tremendous help. I'll do some research this weekend and see what I can figure. I may come back to you if I'm still struggling on Monday, if that's ok with you.

I'll fix up the structure this weekend as well. Really appreciate the help.

**Comment by tracker1** [comment]
from a command prompt, inside the directory in question... you can run `npm init` being a git repo, it should detect most of the settings (other than your license)... from there you should be able to, for example `npm install --save-dev YOURCSSMINUTIL` which will create a `devDependency` in the package.json

Edit your `package.json` (there will be a `scripts` section, that generates a test script by default.. you can add a `build` script that could be something like `node ./build.js` where build.js actually copies the source to a `dist` folder, then creates a minified version.... you may want to look at, for example [gulp for css minification](http://alfanso.com/minify-your-final-css-file-using-gulp-js/).

You can also add an `.npmigore` file for npm, as well as the `ignore` section in the bower config to not include the source files, and build scripts in the final package (npm ignore bower file, bower ignores npm bits).

I don't have a good public css project, or I would refer you to that... you can always look at the [less project](https://github.com/less/less.js) or [bootstrap](https://github.com/twbs/bootstrap) which have both bower and npm publishing.

I can't speak for anyone else, but I tend to just favor using npm alone, not bower for all my dependencies, and my build process will bring in the appropriate files from `./node_modules/MODULE/dist/module.min.foo` ... which imho is just as clean as using bower, without the additional dependency (since bower already requires node/npm).

---

Also of note, if you have a dev dependency on a module, you don't need to install globally, and can use the scripts section to specify something like `less ...` where `less` is the module name... running `npm run less` where less is the name of the scripts (like build above)...  npm will look to the executable scripts for the local modules first before passing to the OS...

---

`npm install --save-dev less`

edit package.json

``` js
{
...
  "scripts": {
    "compile-less":"less ./foo.css > ./foo.min.css"
    ...
  }
...
}
```

`npm run compile-less`

---

It works pretty well...

**Comment by cmaddux** [comment]
Wow, that's an enormous help. I'll work through this tomorrow and Sunday. I think I should be able to get the package.json started no problem and I'll make sure to take a look at bootstrap if I get stuck. Really appreciate the help (and going slow for me), I'll get to it this weekend and see what I can sort out.

**Comment by cmaddux** [comment]
I went ahead and added the package.json and a minifier script (gulpfile.js) that uses gulp to minify littlebox.css and adds the newly minified file to the build folder as littlebox.min.css. Would you be willing to take a look at the changes?

A couple of things I wasn't sure about:
1. In the package.js file, I've added "build": "node gulpfile.js" to the "scripts" section. Will this run the gulpfile whenever a change is made to littlebox.css? I also added a watch function to the gulpfile, maybe that's all I need?
2. I didn't add a .npmignore file, I can do some research on that this week, but I added the node_modules folder and gulpfile.js to the ignore section of bower.

Hopefully you can see the changes in the package-minifier-scripts-ft branch. If you have any advice on improving my branching and workflow, that would be a huge help as well.

Thanks again!

**Comment by tracker1** [comment]
see the related pull request.. :-)  It's a bit overloaded, as I added a gitignore file and removed the node_modules files.

**Comment by cmaddux** [comment]
Once I update the README for contributing via npm and if the .less changes to the gulp script seems ok, is there anything else you can think of that should be added in relation to this issue? If not, I'll close go ahead and close it once the README update is set. Thanks again for all of your help!

**Comment by tracker1** [comment]
works for me... thanks for your work in making this project.
