### ISSUE TITLE
The Swiss flag should be a square

### ISSUE THREAD

**Issue by bewuethr** [cmaddux/littlebox#8]
But to be fair, almost no flag collection gets that right.

**Comment by cmaddux** [comment]
Yeah should be pretty straight forward to fix that on though, not sure how I missed it. Working on it now. Thanks!

**Comment by cmaddux** [comment]
Updated the Swiss flag, should be all set now. Thanks for checking it out.

**Comment by bewuethr** [comment]
:thumbsup: Cool, thanks!
